/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PYQ = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'downloadUrl' : IDL.Text,
  'paperId' : IDL.Nat,
});
export const Paper = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Unit = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'paperId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllPYQs' : IDL.Func([], [IDL.Vec(PYQ)], ['query']),
  'getPYQsByPaper' : IDL.Func([IDL.Nat], [IDL.Vec(PYQ)], ['query']),
  'getPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
  'getUnitsByPaper' : IDL.Func([IDL.Nat], [IDL.Vec(Unit)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PYQ = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'downloadUrl' : IDL.Text,
    'paperId' : IDL.Nat,
  });
  const Paper = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Unit = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'paperId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllPYQs' : IDL.Func([], [IDL.Vec(PYQ)], ['query']),
    'getPYQsByPaper' : IDL.Func([IDL.Nat], [IDL.Vec(PYQ)], ['query']),
    'getPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
    'getUnitsByPaper' : IDL.Func([IDL.Nat], [IDL.Vec(Unit)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };